// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Domain struct {
	Domain             string
	Status             string
	CompanyName        sql.NullString
	Country            sql.NullString
	ScamSources        []string
	ScamType           sql.NullString
	VerifiedAt         sql.NullTime
	VerifiedBy         sql.NullString
	VerificationMethod sql.NullString
	ExpiresAt          sql.NullTime
	RiskScore          sql.NullString
	Reasons            []string
	Metadata           pqtype.NullRawMessage
	CreatedAt          sql.NullTime
	UpdatedAt          sql.NullTime
	LastCheckAt        sql.NullTime
}

type PendingModeration struct {
	Domain         string
	CheckID        uuid.UUID
	Reasons        []string
	SourceModules  []string
	Priority       sql.NullInt32
	Status         sql.NullString
	AssignedTo     sql.NullString
	SubmittedAt    sql.NullTime
	ResolvedAt     sql.NullTime
	ModeratorNotes sql.NullString
	CreatedAt      sql.NullTime
}
