// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: domain.sql

package repository

import (
	"context"

	"github.com/lib/pq"

	"github.com/ItsXomyak/scam-list/internal/modules/domains/repository/models"
)

func (q *Queries) CreateDomain(ctx context.Context, arg models.CreateDomainParams) (models.DomainDB, error) {
	row := q.db.QueryRowContext(ctx, models.СreateDomain,
		arg.Domain,
		arg.CompanyName,
		arg.Country,
		pq.Array(arg.ScamSources),
		arg.ScamType,
		arg.VerifiedAt,
		arg.VerifiedBy,
		arg.VerificationMethod,
		arg.ExpiresAt,
		arg.RiskScore,
		pq.Array(arg.Reasons),
		arg.Metadata,
		arg.LastCheckAt,
	)
	var i models.DomainDB
	err := row.Scan(
		&i.Domain,
		&i.Status,
		&i.CompanyName,
		&i.Country,
		pq.Array(&i.ScamSources),
		&i.ScamType,
		&i.VerifiedAt,
		&i.VerifiedBy,
		&i.VerificationMethod,
		&i.ExpiresAt,
		&i.RiskScore,
		pq.Array(&i.Reasons),
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastCheckAt,
	)
	return i, err
}

func (q *Queries) DeleteDomain(ctx context.Context, domain string) error {
	_, err := q.db.ExecContext(ctx, models.DeleteDomain, domain)
	return err
}

func (q *Queries) GetDomain(ctx context.Context, domain string) (models.DomainDB, error) {
	row := q.db.QueryRowContext(ctx, models.GetDomain, domain)
	var i models.DomainDB
	err := row.Scan(
		&i.Domain,
		&i.Status,
		&i.CompanyName,
		&i.Country,
		pq.Array(&i.ScamSources),
		&i.ScamType,
		&i.VerifiedAt,
		&i.VerifiedBy,
		&i.VerificationMethod,
		&i.ExpiresAt,
		&i.RiskScore,
		pq.Array(&i.Reasons),
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastCheckAt,
	)
	return i, err
}

func (q *Queries) GetDomainsByRiskScore(ctx context.Context, arg models.GetDomainsByRiskScoreParams) ([]models.DomainDB, error) {
	rows, err := q.db.QueryContext(ctx, models.GetDomainsByRiskScore,
		arg.RiskScore,
		arg.RiskScore_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []models.DomainDB
	for rows.Next() {
		var i models.DomainDB
		if err := rows.Scan(
			&i.Domain,
			&i.Status,
			&i.CompanyName,
			&i.Country,
			pq.Array(&i.ScamSources),
			&i.ScamType,
			&i.VerifiedAt,
			&i.VerifiedBy,
			&i.VerificationMethod,
			&i.ExpiresAt,
			&i.RiskScore,
			pq.Array(&i.Reasons),
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastCheckAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

func (q *Queries) GetDomainsByStatus(ctx context.Context, arg models.GetDomainsByStatusParams) ([]models.DomainDB, error) {
	rows, err := q.db.QueryContext(ctx, models.GetDomainsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []models.DomainDB
	for rows.Next() {
		var i models.DomainDB
		if err := rows.Scan(
			&i.Domain,
			&i.Status,
			&i.CompanyName,
			&i.Country,
			pq.Array(&i.ScamSources),
			&i.ScamType,
			&i.VerifiedAt,
			&i.VerifiedBy,
			&i.VerificationMethod,
			&i.ExpiresAt,
			&i.RiskScore,
			pq.Array(&i.Reasons),
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastCheckAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

func (q *Queries) GetDomainsForRecheck(ctx context.Context, arg models.GetDomainsForRecheckParams) ([]models.DomainDB, error) {
	rows, err := q.db.QueryContext(ctx, models.GetDomainsForRecheck, arg.LastCheckAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []models.DomainDB
	for rows.Next() {
		var i models.DomainDB
		if err := rows.Scan(
			&i.Domain,
			&i.Status,
			&i.CompanyName,
			&i.Country,
			pq.Array(&i.ScamSources),
			&i.ScamType,
			&i.VerifiedAt,
			&i.VerifiedBy,
			&i.VerificationMethod,
			&i.ExpiresAt,
			&i.RiskScore,
			pq.Array(&i.Reasons),
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastCheckAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

func (q *Queries) MarkDomainAsScam(ctx context.Context, arg models.MarkDomainAsScamParams) (models.DomainDB, error) {
	row := q.db.QueryRowContext(ctx, models.MarkDomainAsScam,
		arg.Domain,
		pq.Array(arg.ScamSources),
		arg.ScamType,
		arg.RiskScore,
		pq.Array(arg.Reasons),
	)
	var i models.DomainDB
	err := row.Scan(
		&i.Domain,
		&i.Status,
		&i.CompanyName,
		&i.Country,
		pq.Array(&i.ScamSources),
		&i.ScamType,
		&i.VerifiedAt,
		&i.VerifiedBy,
		&i.VerificationMethod,
		&i.ExpiresAt,
		&i.RiskScore,
		pq.Array(&i.Reasons),
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastCheckAt,
	)
	return i, err
}

func (q *Queries) UpdateDomainStatus(ctx context.Context, arg models.UpdateDomainStatusParams) (models.DomainDB, error) {
	row := q.db.QueryRowContext(ctx, models.UpdateDomainStatus,
		arg.Domain,
		arg.Status,
		arg.RiskScore,
		pq.Array(arg.Reasons),
	)
	var i models.DomainDB
	err := row.Scan(
		&i.Domain,
		&i.Status,
		&i.CompanyName,
		&i.Country,
		pq.Array(&i.ScamSources),
		&i.ScamType,
		&i.VerifiedAt,
		&i.VerifiedBy,
		&i.VerificationMethod,
		&i.ExpiresAt,
		&i.RiskScore,
		pq.Array(&i.Reasons),
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastCheckAt,
	)
	return i, err
}

func (q *Queries) VerifyDomain(ctx context.Context, arg models.VerifyDomainParams) (models.DomainDB, error) {
	row := q.db.QueryRowContext(ctx, models.VerifyDomain,
		arg.Domain,
		arg.VerifiedAt,
		arg.VerifiedBy,
		arg.VerificationMethod,
		arg.ExpiresAt,
		arg.RiskScore,
		pq.Array(arg.Reasons),
	)
	var i models.DomainDB
	err := row.Scan(
		&i.Domain,
		&i.Status,
		&i.CompanyName,
		&i.Country,
		pq.Array(&i.ScamSources),
		&i.ScamType,
		&i.VerifiedAt,
		&i.VerifiedBy,
		&i.VerificationMethod,
		&i.ExpiresAt,
		&i.RiskScore,
		pq.Array(&i.Reasons),
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastCheckAt,
	)
	return i, err
}