version: '3'
services:
  scam_app:
    container_name: ${PROJECT_NAME}
    build: .
    env_file:
      - .env
    restart: always
    depends_on:
      postgresql:
        condition: service_healthy

  postgresql:
    image: postgres:16.3
    hostname: ${POSTGRES_HOST}
    ports:
      - 5432:${POSTGRES_PORT}
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command:
      [
        '-path',
        '/migrations/postgres',
        '-database',
        'postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable',
        'up',
      ]
    depends_on:
      postgresql:
        condition: service_healthy
